### ISSUE TITLE
secure_config.ini missing in repo?

### ISSUE THREAD

**Issue by asafpm** [colab-chat/colab-server#8]
When trying to initialise the server with  `python3 manage.py create_db` I get the following error:

```
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from colab_server import create_app, db
  File "/data/Programming/Collaboration/colab-chat/colab-server/colab_server/__init__.py", line 5, in <module>
    from config import config
  File "/data/Programming/Collaboration/colab-chat/colab-server/config.py", line 24, in <module>
    @secure_config
  File "/data/Programming/Collaboration/colab-chat/colab-server/config.py", line 13, in secure_config
    secret_key = config_parser['db']['secret_key']
  File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'db'
```

It seems that in config.py it looks for a file called `secure_config.ini` which doesn't seem to be in the repo.

**Comment by AntonPiccardoSelg** [comment]
@asafpm check slack. The secure config should not be in the repo
